---
# cloud_controller_uri: api.vcap.me
service:
  name: membase
  version: "1.7.0"
  description: 'Membase database service'
  plans: ['free']
  tags: ['membase', 'membase-1.7.0', 'nosql', 'memcache', 'memcached']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
membase_mbus: nats://localhost:4222
service_mbus: nats://localhost:4222
pid: /var/vcap/sys/run/membase_service.pid
node_timeout: 2
# allow_over_provisioning: false
